name: Lua lint

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
      - "hotfix/**"
      - "bugfix/**"
      - "support/**"
      - "update/**"
    paths:
      - "script/**"
      - ".luacheckrc"
  pull_request:
    branches:
      - main
      - develop
      - "feature/**"
      - "hotfix/**"
      - "bugfix/**"
      - "support/**"
      - "update/**"
  workflow_dispatch:

jobs:
  db-check:
    uses: Warhammer-Mods/workflows/.github/workflows/lua-lint.yml@v1
    with:
      paths: script
      pr_enabled: true
      automerge_enabled: false # Disabled for the develop branch
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
